security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        our_db_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            provider: our_db_provider
            logout:
                path:   /logout
                target: /
        secured_area:
            form_login:
                csrf_token_generator: security.csrf.token_manager

    access_control:
            - { path: ^/trick/new, role: ROLE_USER }
            - { path: ^/trick/.*/edit, role: ROLE_USER }
            - { path: ^/trick/.*/delete, role: ROLE_USER }
            - { path: ^/user/edit, role: ROLE_USER }
            - { path: ^/user/edit/delete, role: ROLE_USER }
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

            - { path: ^/reset-password-request, role: ROLE_USER }

            - { path: ^/reset-password, role: ROLE_USER, methods: [POST, PUT] }


