App\Entity\Trick:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: { message: "N'oublies pas de donner un nom au trick" }
        description:
            - NotBlank: { message: "N'oublies pas de décrire le trick pour que l'on sache de quoi il sagit" }
        trickGroup:
            - NotBlank: { message: "N'oublies pas de saisir une catégorie" }

App\Entity\Comment:
    properties:
        content:
            - NotBlank: { message: "Ton commentaire est vide..." }

App\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
    properties:
        username:
            - NotBlank:
                message: "Il faut entre ton pseudo ;)"
                groups: ['registration']
        email:
            - NotBlank:
                message: "Il faut entrer ton email"
        plainPassword:
            - NotBlank:
                message: "Il faut entrer ton mot de passe pour sécuriser ton compte"
                groups: ['registration']
        firstname:
            - NotBlank:
                message: "Il faut entrer ton mot de passe pour sécuriser ton compte"
