trick_list:
    path: /
    controller: App\Controller\TrickController::listAction

trick_create:
    path: /trick/new
    controller: App\Controller\TrickController::createAction

trick_show:
    path: /trick/{slug}
    controller: App\Controller\TrickController::showAction

trick_edit:
    path: /trick/{slug}/edit
    controller: App\Controller\TrickController::editAction

trick_delete:
    path: /trick/{slug}/delete
    controller: App\Controller\TrickController::deleteAction

user_edit:
    path: /user/edit
    controller: App\Controller\UserController:editAction

register:
    path: /register
    controller: App\Controller\RegistrationController:registrationAction

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout

admin:
    path: /admin
    controller: App\Controller\SecurityController::admin
