trick_list:
    path: /
    controller: App\Controller\TrickController::listAction

trick_create:
    path: /trick/new
    controller: App\Controller\TrickController::createAction

trick_show:
    path: /trick/{slug}
    controller: App\Controller\TrickController::showAction

trick_edit:
    path: /trick/{slug}/edit
    controller: App\Controller\TrickController::editAction

trick_delete:
    path: /trick/{slug}/delete
    controller: App\Controller\TrickController::deleteAction

user_edit:
    path: /user/edit
    controller: App\Controller\UserController:editAction

user_avatar_delete:
    path: /user/edit/delete
    controller: App\Controller\UserController:deleteAvatarAction

register:
    path: /register
    controller: App\Controller\RegistrationController:registrationAction

account_activation:
    path: /account-activation
    controller: App\Controller\RegistrationController:accountActivation

login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /logout

reset_password:
    path: /reset-password
    controller: App\Controller\SecurityController::resetPassword

reset_password_request:
    path: /reset-password-request
    controller: App\Controller\SecurityController::resetPasswordRequest