trick_list:
    path: /
    controller: App\Controller\TrickController::listAction

trick_create:
    path: /trick/new
    controller: App\Controller\TrickController::createAction

trick_show:
    path: /trick/{slug}
    controller: App\Controller\TrickController::showAction

trick_edit:
    path: /trick/{slug}/edit
    controller: App\Controller\TrickController::editAction