trick_list:
    path: /
    controller: App\Controller\TrickController::listAction

trick_create:
    path: /trick/new
    controller: App\Controller\TrickController::createAction

trick_show:
    path: /trick/{trickName}
    controller: App\Controller\TrickController::showAction

