App\Entity\Comment:
  type: entity
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    content:
      type: text
      length: 2000
      nullable: false
    createdAt:
      type: datetime
  manyToOne:
    trick:
      targetEntity: App\Entity\Trick
      inversedBy: comments
      joinColumn:
        nullable: true
      cascade: ["persist", "remove"]
    user:
      targetEntity: App\Entity\User
      inversedBy: comments
      joinColumn:
        nullable: true
      cascade: ["persist", "remove"]



