App\Entity\Image:
  type: entity
  repositoryClass: App\Repository\ImageRepository
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    filename:
      type: string
      length: 100
      nullable: true
    caption:
      type: string
      length: 100
      nullable: true
  manyToOne:
    trick:
      targetEntity: App\Entity\Trick
      inversedBy: images
      joinColumn:
        nullable: true
      cascade: ["persist", "remove"]
  oneToOne:
    user:
      targetEntity: App\Entity\User
      inversedBy: image
      joinColumn:
        nullable: true


