App\Entity\Trick:
  type: entity
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    name:
      type: string
      length: 100
    description:
      type: text
      length: 2000
    group:
      column: trick_group
      type: string
      lenght: 100
    createdAt:
      type: datetime
  manyToOne:
    user:
      targetEntity: App\Entity\User
      inversedBy: tricks
      joinColumn:
        nullable: true
  oneToMany:
    comments:
      targetEntity: App\Entity\Comment
      mappedBy: trick
    videos:
      targetEntity: App\Entity\Video
      mappedBy: trick
    images:
      targetEntity: App\Entity\Image
      mappedBy: trick

