App\Entity\User:
  table: app_user
  type: entity
  repositoryClass: App\Repository\UserRepository
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    username:
      type: string
      length: 100
    email:
      type: string
      length: 100
    firstname:
      type: string
      length: 100
    lastname:
      type: string
      length: 100
    password:
      type: string
      length: 100
    avatar:
      type: string
      length: 100
      nullable: true
    roles:
      type: array
      length: 100
    isActive:
      type: boolean
      default: false
    createdAt:
      type: datetime
  oneToMany:
    tricks:
      targetEntity: App\Entity\Trick
      mappedBy: user
      cascade: ["persist", "remove"]
    comments:
      targetEntity: App\Entity\Comment
      mappedBy: user
      cascade: ["persist", "remove"]
  oneToOne:
    image:
      targetEntity: Image
      mappedBy: user
      cascade: ["persist", "remove"]
