App\Entity\User:
  table: app_user
  type: entity
  repositoryClass: App\Repository\UserRepository
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    username:
      type: string
      length: 100
      unique: true
    email:
      type: string
      length: 100
      unique: true
    firstname:
      type: string
      length: 100
      nullable: true
    lastname:
      type: string
      length: 100
      nullable: true
    password:
      type: string
      length: 100
    avatar:
      type: string
      length: 100
      nullable: true
    roles:
      type: array
      length: 100
    isActive:
      type: boolean
      default: true
    createdAt:
      type: datetime
    resetPasswordToken:
      type: string
      length: 25
      nullable: true
    resetPasswordTokenTimestamp:
      type: datetime
      nullable: true
    activationToken:
      type: string
      length: 25
      nullable: true
  oneToMany:
    tricks:
      targetEntity: App\Entity\Trick
      mappedBy: user
    comments:
      targetEntity: App\Entity\Comment
      mappedBy: user
  oneToOne:
    image:
      targetEntity: Image
      mappedBy: user
