App\Entity\User:
  type: entity
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    username:
      type: string
      length: 100
    email:
      type: string
      scale: 100
    firstname:
      type: string
      scale: 100
    lastname:
      type: string
      scale: 100
    password:
      type: string
      scale: 20
    avatar:
      type: string
      scale: 100
      nullable: true
    role:
      type: string
      scale: 100
    active:
      type: boolean
    createdAt:
      type: datetime